# Generated by Django 5.2.9 on 2025-12-21 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='System Name')),
                ('supply_temperature', models.IntegerField(default=70, help_text='Vorlauftemperatur', verbose_name='Supply Temperature (°C)')),
                ('return_temperature', models.IntegerField(default=55, help_text='Rücklauftemperatur', verbose_name='Return Temperature (°C)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Room Name')),
                ('area_sqm', models.FloatField(verbose_name='Area (m²)')),
                ('height_m', models.FloatField(default=2.5, verbose_name='Ceiling Height (m)')),
                ('target_temp', models.FloatField(default=20.0, verbose_name='Target Temperature (°C)')),
                ('insulation_quality', models.CharField(choices=[('poor', 'Poor (Old Building)'), ('average', 'Average (Renovated)'), ('good', 'Good (Modern/Insulated)')], default='average', max_length=20)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hyd_balancing.heatingsystem')),
            ],
        ),
        migrations.CreateModel(
            name='Radiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Window Left', max_length=100, verbose_name='Radiator Identifier')),
                ('width_mm', models.IntegerField(blank=True, null=True, verbose_name='Width (mm)')),
                ('height_mm', models.IntegerField(blank=True, null=True, verbose_name='Height (mm)')),
                ('radiator_type', models.CharField(choices=[('10', 'Type 10'), ('11', 'Type 11'), ('21', 'Type 21'), ('22', 'Type 22'), ('33', 'Type 33'), ('underfloor', 'Underfloor Heating')], default='22', max_length=20)),
                ('required_flow_rate', models.FloatField(blank=True, null=True, verbose_name='Required Flow Rate (l/h)')),
                ('valve_setting', models.CharField(blank=True, max_length=50, null=True, verbose_name='Recommended Valve Setting')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiators', to='hyd_balancing.room')),
            ],
        ),
    ]
