# Generated by Django 5.2.9 on 2025-12-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyd_balancing', '0002_heatingsystem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='custom_insulation_value',
            field=models.FloatField(blank=True, help_text="Only used if 'Custom' is selected above", null=True, verbose_name='Custom Insulation Value (W/m²)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='insulation_quality',
            field=models.CharField(choices=[('poor', 'Poor (Old Building)'), ('average', 'Average (Renovated)'), ('good', 'Good (Modern/Insulated)'), ('custom', 'Custom Value (W/m²)')], default='average', max_length=20),
        ),
    ]
