# Generated by Django 5.2.9 on 2025-12-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyd_balancing', '0003_room_custom_insulation_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiator',
            name='calculated_load_watts',
            field=models.FloatField(blank=True, null=True, verbose_name='Calculated Load (W)'),
        ),
    ]
