# Generated by Django 5.2.9 on 2025-12-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyd_balancing', '0004_radiator_calculated_load_watts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatingsystem',
            name='name',
            field=models.CharField(help_text='A name to identify this house or apartment.', max_length=100, verbose_name='System Name'),
        ),
        migrations.AlterField(
            model_name='heatingsystem',
            name='return_temperature',
            field=models.IntegerField(default=55, help_text='The temperature of the water returning to the boiler (Rücklauftemperatur). The difference to supply temp affects flow rates.', verbose_name='Return Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='heatingsystem',
            name='supply_temperature',
            field=models.IntegerField(default=70, help_text='The temperature of the water leaving the boiler (Vorlauftemperatur). Higher values are common in older buildings.', verbose_name='Supply Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='calculated_load_watts',
            field=models.FloatField(blank=True, help_text='The heat energy this specific radiator must deliver.', null=True, verbose_name='Calculated Load (W)'),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='height_mm',
            field=models.IntegerField(blank=True, help_text='Height of the radiator in millimeters.', null=True, verbose_name='Height (mm)'),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='name',
            field=models.CharField(help_text='e.g. Window Left, North Wall. Helps you identify the valve to adjust.', max_length=100, verbose_name='Radiator Identifier'),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='radiator_type',
            field=models.CharField(choices=[('10', 'Type 10'), ('11', 'Type 11'), ('21', 'Type 21'), ('22', 'Type 22'), ('33', 'Type 33'), ('underfloor', 'Underfloor Heating')], default='22', help_text='Type determines heat output. 22 is the most common double-panel radiator.', max_length=20),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='required_flow_rate',
            field=models.FloatField(blank=True, help_text='The amount of water that should pass through the valve per hour.', null=True, verbose_name='Required Flow Rate (l/h)'),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='valve_setting',
            field=models.CharField(blank=True, help_text='The pre-setting to apply to your radiator valve.', max_length=50, null=True, verbose_name='Recommended Valve Setting'),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='width_mm',
            field=models.IntegerField(blank=True, help_text='Width of the radiator in millimeters.', null=True, verbose_name='Width (mm)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='area_sqm',
            field=models.FloatField(help_text='Total floor area of the room. Can be calculated from length and width.', verbose_name='Area (m²)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='custom_insulation_value',
            field=models.FloatField(blank=True, help_text='Specify the exact heat demand in Watts per square meter.', null=True, verbose_name='Custom Insulation Value (W/m²)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='height_m',
            field=models.FloatField(default=2.5, help_text='The vertical height of the room, used for volume estimations.', verbose_name='Ceiling Height (m)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='insulation_quality',
            field=models.CharField(choices=[('poor', 'Poor (Old Building)'), ('average', 'Average (Renovated)'), ('good', 'Good (Modern/Insulated)'), ('custom', 'Custom Value (W/m²)')], default='average', help_text='Affects how much heat (W/m²) is needed to maintain temperature.', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='e.g. Living Room, Bedroom 1', max_length=100, verbose_name='Room Name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='target_temp',
            field=models.FloatField(default=20.0, help_text='Desired room temperature. Usually 20°C for living rooms, 22°C for bathrooms.', verbose_name='Target Temperature (°C)'),
        ),
    ]
