# Generated by Django 5.2.9 on 2025-12-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyd_balancing', '0005_alter_heatingsystem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiator',
            name='load_percentage',
            field=models.IntegerField(default=100, help_text="Percentage of the room's total heat load this radiator should cover. Total for all radiators in a room should be 100%.", verbose_name='Load Percentage (%)'),
        ),
    ]
