# Generated by Django 5.2.9 on 2025-12-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyd_balancing', '0006_radiator_load_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiator',
            name='max_capacity_watts',
            field=models.FloatField(blank=True, null=True, verbose_name='Max Capacity (W)'),
        ),
    ]
