# Generated by Django 5.2.9 on 2025-12-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyd_balancing', '0007_radiator_max_capacity_watts'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiator',
            name='area_sqm',
            field=models.FloatField(blank=True, help_text='For underfloor heating: The floor area covered by this specific heating loop.', null=True, verbose_name='Area (m²)'),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='height_mm',
            field=models.IntegerField(blank=True, help_text='Height of the radiator in millimeters. Not needed for underfloor heating.', null=True, verbose_name='Height (mm)'),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='width_mm',
            field=models.IntegerField(blank=True, help_text='Width of the radiator in millimeters. Not needed for underfloor heating.', null=True, verbose_name='Width (mm)'),
        ),
    ]
