# Generated by Django 5.2.9 on 2025-12-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyd_balancing', '0008_radiator_area_sqm_alter_radiator_height_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiator',
            name='pipe_length_m',
            field=models.IntegerField(blank=True, help_text='Total length of the heating pipe in this loop.', null=True, verbose_name='Pipe Length (m)'),
        ),
        migrations.AddField(
            model_name='radiator',
            name='pipe_spacing_mm',
            field=models.IntegerField(blank=True, choices=[(50, '50mm'), (100, '100mm'), (150, '150mm'), (200, '200mm'), (250, '250mm')], default=150, help_text='Distance between pipes (Verlegeabstand).', null=True, verbose_name='Pipe Spacing (mm)'),
        ),
    ]
