# Generated by Django 5.2.9 on 2025-12-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyd_balancing', '0009_radiator_pipe_length_m_radiator_pipe_spacing_mm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiator',
            name='area_sqm',
        ),
        migrations.RemoveField(
            model_name='radiator',
            name='pipe_spacing_mm',
        ),
    ]
