# Generated by Django 5.2.9 on 2025-12-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyd_balancing', '0010_remove_radiator_area_sqm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiator',
            name='area_sqm',
            field=models.FloatField(blank=True, help_text='For underfloor heating: The floor area covered by this specific heating loop.', null=True, verbose_name='Area (m²)'),
        ),
    ]
