# Generated by Django 5.2.9 on 2025-12-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyd_balancing', '0011_radiator_area_sqm'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiator',
            name='nominal_capacity_watts',
            field=models.FloatField(blank=True, help_text='Power at standard 75/65/20 temperatures.', null=True, verbose_name='Nominal Power (W)'),
        ),
    ]
