# Generated by Django 5.2.9 on 2026-01-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyd_balancing', '0012_radiator_nominal_capacity_watts'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatingsystem',
            name='max_valve_setting',
            field=models.IntegerField(default=6, help_text='The maximum setting value for the thermostat valves (usually 6, sometimes 10 or 15).', verbose_name='Max Valve Setting'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.CharField(blank=True, help_text='e.g., Ground Floor, 1st Floor', max_length=50, null=True, verbose_name='Floor'),
        ),
    ]
