# Generated by Django 5.2.9 on 2026-01-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyd_balancing', '0013_heatingsystem_max_valve_setting_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='external_walls',
            field=models.IntegerField(default=1, help_text='Number of walls facing outside (0-4). Affects heat demand.', verbose_name='External Walls'),
        ),
    ]
